### ISSUE TITLE
Add Author Model

### ISSUE THREAD

**Issue by foglabs-zen** [WGBH-MLA/ov_wag#17]
Because:
The design for OV Redesign features author information consisting of:
-Author name
-Author img
-Author bio

One author might be responsible for multiple exhibits/special collections, should be a separate model to avoid duplicating data. The design does not depict any instances of multiple contributing authors for one Exhibit, but it would make sense to allow for multiple authors to be connected to an exhibit.

Done When:
We have added a wagtail model to represent Authors and the Exhibit model has_many Authors.

**Comment by afred** [comment]
Helpful tutorial on adding new types of non-Page models to Wagtail, complete with edit interfaces. Very straightforward: https://learnwagtail.com/tutorials/how-register-django-model-wagtails-modeladmin/
