### ISSUE TITLE
Basic deployment of front-end in Rancher

### ISSUE THREAD

**Issue by afred** [WGBH-MLA/ov_wag#4]
External Rancher in AWS accessible at https://rancherext.wgbh.org/p/c-7qk7g:p-lpkts/workloads

### Done when
* Latest code is deployable to external Rancher in AWS
* Latest is actually deployed

**Comment by mrharpo** [comment]
Latest code is available from Rancher:

http://ovfrontend.k8s.wgbhdigital.org/
